import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./styles/globals.css";
import PrelineScript from "./components/preline/PrelineScript";
import SessionProvider from "./components/nextauth-wrapper/SessionProvider";
import { ProductContextProvider } from "./context/products/ProductContext";
import { UserContextProvider } from "./context/users/UserContext";
import { Toaster } from "./components/ui/sonner";


const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={montserrat.className}
      >
     
        <SessionProvider>
        <UserContextProvider>
        <ProductContextProvider>
        {children}
        </ProductContextProvider>
        </UserContextProvider>
        </SessionProvider>
        <Toaster />
      </body>
      <PrelineScript />
    </html>
  );
}
