import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./styles/globals.css";
import PrelineScript from "./components/preline/PrelineScript";


const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={montserrat.className}
      >
        {children}
      </body>
      <PrelineScript />
    </html>
  );
}
